platform :ios, '9.0'
use_frameworks!

def install_pods
  pod 'AlamofireImage', '3.2.0'
end

target 'ios-AlamofireImage-demo' do
  install_pods
  # Pods for ios-AlamofireImage-demo

  target 'ios-AlamofireImage-demoTests' do
    install_pods
    # Pods for testing
  end

end
